# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
patreon: jahed
liberapay: jahed
custom: [
  "https://paypal.me/jahed/5",
  "https://jahed.dev/donate"
]
